层层"""
Django settings for HelloWorld project.

Generated by 'django-admin startproject' using Django 1.8.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'p4s-ewqu!g12=tu@p9*#jc)s8ix+_qi4*p+v_e90$h8bv7m2@x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'books',
    'debug_toolbar',
)
# + ('debug_toolbar.apps.DebugToolbarConfig',) #或者这种
# 添加调试工具
INTERNAL_IPS = ("127.0.0.1", )

# 默认的Django Debug Toolbar需要用到jquery，
# 是使用google的jquery，我们可能访问不了，那么我们需要修改
CONFIG_DEFAULTS = {
    # Toolbar options
    'JQUERY_URL': r'/static/js/jquery-3.3.1.min.js',  # 本地jquery

    'SHOW_TOOLBAR_CALLBACK': lambda x: True,  # 显示调试栏
}
DEBUG_TOOLBAR_CONFIG = {
    'JQUERY_URL': r"http://code.jquery.com/jquery-2.1.1.min.js"}
# 如果本地js不能加载,加上如上网站地址

# MIDDLEWARE_CLASSES
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # 自己添加(2018.05.23,为了admin网站显示中文)
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',  # 解决post(403),csrf验证
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',  # 2.0改变
    'django.contrib.messages.middleware.MessageMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',  # 调试工具中间件
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'HelloWorld.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates').replace('\\', '/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                # "django.core.context_processors.request",
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'HelloWorld.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mydb',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': '127.0.0.1',
        'PORT ': '3306',
    }
}
#'ENGINE': 'django.db.backends.sqlite3',
#'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

# 设置session
SESSION_COOKIE_AGE = 60 * 30  # (和下面那个只能二选一)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # 关闭浏览器,则COOKIE失效
# 两个参数只有在 SESSION_SAVE_EVERY_REQUEST 为 True 时才有效。
SESSION_SAVE_EVERY_REQUEST = True

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'  # os.path.join(os.path.dirname(__file__),'static')
STATICFILES_DIRS = (BASE_DIR, 'static')
# STATIC_ROOT = '/home/tarena/HelloWorld/static'

# 上传文件(图片)并显示在网页的设置
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
# media是约定成俗的文件夹名
MEDIA_URL = "/media/"   # 跟STATIC_URL类似，指定用户可以通过这个路径找到文件

# 生成的验证码保存的路径
VERIFICATION_CODE_IMGS_DIR = os.path.join(BASE_DIR, 'static', 'verifCode')

# 显示设置调试工具不要调整settings中的设置
DEBUG_TOOLBAR_PATCH_SETTINGS = False
